theme: jekyll-theme-leap-day

title: [Monitora]

description: [Esse é um site que disponibilizamos para os nossos usuários com várias dicas de como realizar o armazenamento dos alimentos de forma correta.]

github:
  zip_url: http://example.com/download.zip
  another_url: another value
