theme: jekyll-theme-minimal

logo: [https://lh3.googleusercontent.com/pw/ACtC-3epXjaK7179vrdzPiFQPIRMq5aoIo5ybBnfSIZQikjG7-TQ0rjAUgejiFuPzY3bb16rHReCftd9uw9fNa-zEGRrBgyvFrOgAqRQ7Z7t0J34-Pp2OLaJY9D52RM4BL-ugl76myISkmaBNXZsTnLvWSZp=w1112-h625-no?authuser=0]

